In [1]:
import numpy as np

## Exercise 1

In [2]:
x = np.arange(16).reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
# Subset to get the 2x2 with 5, 6, 9, 10 as elements

x[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [4]:
x[[1,2], [1,2]]

array([ 5, 10])

In [7]:
x[[1,2],][:,[1,2]]

array([[ 5,  6],
       [ 9, 10]])

In [9]:
x[[3,3,3,0],]

array([[12, 13, 14, 15],
       [12, 13, 14, 15],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3]])

## Exercise 2

We will now use this to attempt a simple brute force approach to numerical optimization, define a grid of points using meshgrid() to approximate the minima the following function:

$$f(x,y)=(1−x)^2+100(y−x^2)^2$$

Considering values of $x, y \in (−1,3)$, which values of $x, y$ minimize this function?

In [12]:
pts = np.linspace(-1, 3, 5000)
x, y = np.meshgrid(pts, pts)

f = (1-x)**2 + 100 * (y-x**2)**2

array([[  404.        ,   403.35718397,   402.71539241, ...,
         9984.80409733,  9994.39846444, 10004.        ],
       [  403.68000001,   403.03743999,   402.39590422, ...,
         9983.2053775 ,  9992.7989766 , 10002.39974396],
       [  403.36012808,   402.71782405,   402.07654408, ...,
         9981.60678572,  9991.19961682, 10000.79961597],
       ...,
       [  403.36012808,   403.9965439 ,   404.63296018, ...,
         3594.40115259,  3600.15782415,  3605.92064018],
       [  403.68000001,   404.31667183,   404.95334391, ...,
         3593.44230468,  3599.19820824,  3604.96025606],
       [  404.        ,   404.63692782,   405.27385569, ...,
         3592.48358482,  3598.23872038,  3604.        ]])

In [16]:
mn = np.min(f)
print(x[f == mn], y[f == mn])

[0.99959992] [0.99959992]


In [18]:
min_i = np.argmin(f, axis=None)
min_i

12497499

In [19]:
print(x.ravel()[min_i], y.ravel()[min_i])

0.9995999199839969 0.9995999199839969


## Example 1

In [20]:
rng = np.random.default_rng(1234)
d = rng.normal(loc=[-1,0,1], scale=[1,2,3], size=(1000,3))
d

array([[-2.60383681,  0.12819983,  3.22267389],
       [-0.84738081,  1.72748778,  9.73929767],
       [-2.47882336,  1.89094595, -3.99840637],
       ...,
       [-0.70173602, -1.00685694,  4.73479258],
       [-2.53070737, -1.61987846, -3.09503767],
       [ 0.20192215, -1.36334125, -1.24706282]])

In [21]:
d.mean(axis=0)

array([-1.0294382 , -0.01396257,  1.01241784])

In [24]:
d.std(axis=0)

array([0.99674719, 2.03222595, 3.10625219])

Standardize the three columns to have mean 0 and std dev 1.

In [26]:
d_std = (d - d.mean(axis=0)) / d.std(axis=0)
d_std.shape

(1000, 3)

In [27]:
print(d_std.mean(0), d_std.std(0))

[ 2.35367281e-17  7.32747196e-18 -1.79078974e-16] [1. 1. 1.]


## Exercise 3

* *A (128 x 128 x 3) + B (3)*:

```
A    128 x 128 x 3
B                3
------------------
A+B  128 x 128 x 3 
```

* A (8 x 1 x 6 x 1) + B (7 x 1 x 5)

```
A    8 x 1 x 6 x 1
B        7 x 1 x 5
------------------
A+B  8 x 7 x 6 x 5
```

* A (2 x 1) + B (8 x 4 x 3)

```
A            2 x 1
B        8 x 4 x 3
------------------
A+B         Error
```

* A (3 x 1) + B (15 x 3 x 5)

```
A            3 x 1
B       15 x 3 x 5
------------------
A+B     15   3   5
```

* A (3) + B (4)

```
A       3
B       4
--------------
A+B   Error
```